Category.create(title: "Love")
Category.create(title: "Inspirational")
Category.create(title: "Funny")
Category.create(title: "Happiness")
Category.create(title: "Friendship")
Category.create(title: "Wisdom")
Category.create(title: "Misc")